### ISSUE TITLE
New 2019 website checklist

### ISSUE THREAD

**Issue by jstoiko** [raml-org/raml-website#86]
Projects:
- [x] add `secondary_link` where possible ([E.g.](https://github.com/raml-org/raml-org/blob/develop/_data/projects.yml#L53))
- [x] review projects [submitted as PRs](https://github.com/raml-org/raml-org/pulls)
- [x] review list of projects, add new projects (make PR)

Playground:
- [x] Rename button next to Monaco editor "Fullscreen" to "Try it out"
- [x] Link both "Try it out" buttons to playground demo
- [x] Pass content of Monaco editor to playground demo

**Comment by postatum** [comment]
@jstoiko 
>  add secondary_link where possible (E.g.)

What is a purpose of `secondary_link`? Where should those links point to? I can only see one example and it points to live demo.

**Comment by jstoiko** [comment]
They could be anything really. For now let’s focus on adding links to official live demos to products that have them.
